server:
  port: 9090

logging:
  level:
    root: info
    bala.signoff: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file.name: logs/my-signoff.log

spring:
  application:
    name: MySignoff
  mongodb:
    uri: mongodb://bala:pass@localhost:27017/demo?authSource=admin
    # # uri: mongodb://root:pass@localhost:27017/demo?authSource=admin
    # uri: mongodb://root:pass@localhost:27017/admin?authSource=admin
